# -*- coding: utf-8 -*-
"""resume.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1igmForJlgdDk1fc7B9OeiMKbLaQnEHA-
"""

# Install all libraries required for the AI Resume Analyzer
!pip install streamlit pdfplumber PyPDF2 python-docx transformers torch pyngrok

# Install required libraries for the AI Resume Analyzer project
!pip install streamlit PyPDF2 python-docx transformers torch pyngrok

# Commented out IPython magic to ensure Python compatibility.
# 
# %%writefile app.py
# 
# # Import required libraries
# import streamlit as st           # For creating the web app interface
# import pdfplumber                # For extracting text from PDF resumes
# from transformers import pipeline # For using AI model to improve text
# 
# 
# # Configure the Streamlit page
# st.set_page_config(page_title="AI Resume Analyzer", page_icon="📄")
# 
# # Title shown in the web application
# st.title("📄 AI Resume Analyzer & Improver")
# 
# 
# # -----------------------------
# # Load AI model (runs only once)
# # -----------------------------
# @st.cache_resource
# def load_model():
#     # Load GPT-2 text generation model
#     generator = pipeline(
#         "text-generation",
#         model="gpt2"
#     )
#     return generator
# 
# # Store the model in memory
# generator = load_model()
# 
# 
# # ---------------------------------
# # Function to extract text from PDF
# # ---------------------------------
# def extract_text(file):
#     text = ""
# 
#     # Open the uploaded PDF file
#     with pdfplumber.open(file) as pdf:
# 
#         # Loop through each page
#         for page in pdf.pages:
# 
#             # Extract text from the page
#             if page.extract_text():
#                 text += page.extract_text()
# 
#     return text
# 
# 
# # ---------------------------------
# # Function to calculate resume score
# # ---------------------------------
# def score_resume(text):
# 
#     score = 0
# 
#     # Important keywords usually expected in resumes
#     keywords = [
#         "python",
#         "java",
#         "project",
#         "experience",
#         "skills",
#         "education",
#         "internship",
#         "team",
#         "leadership"
#     ]
# 
#     # Check if keywords exist in the resume
#     for word in keywords:
#         if word in text.lower():
#             score += 10
# 
#     # Maximum score limited to 100
#     return min(score, 100)
# 
# 
# # ---------------------------------
# # Function to generate suggestions
# # ---------------------------------
# def get_suggestions(text):
# 
#     suggestions = []
# 
#     # Check if important sections exist
#     if "skills" not in text.lower():
#         suggestions.append("Add a Skills section to highlight your abilities.")
# 
#     if "project" not in text.lower():
#         suggestions.append("Include Projects to demonstrate practical work.")
# 
#     if "experience" not in text.lower():
#         suggestions.append("Add Work Experience or Internship.")
# 
#     if "education" not in text.lower():
#         suggestions.append("Mention your Education details clearly.")
# 
#     # If resume is too short
#     if len(text) < 600:
#         suggestions.append("Your resume is short. Add more achievements and responsibilities.")
# 
#     # If everything looks good
#     if len(suggestions) == 0:
#         suggestions.append("Your resume looks good! Add quantified achievements (numbers, results).")
# 
#     return suggestions
# 
# 
# # ---------------------------------
# # Function to improve bullet points
# # ---------------------------------
# def improve_bullet(text):
# 
#     # Prompt sent to the AI model
#     prompt = f"Rewrite this resume bullet professionally: {text}"
# 
#     # Generate improved text using AI
#     result = generator(
#         prompt,
#         max_length=60,
#         num_return_sequences=1
#     )
# 
#     # Return generated result
#     return result[0]["generated_text"]
# 
# 
# # ---------------------------------
# # Extract possible bullet points
# # ---------------------------------
# def extract_bullets(text):
# 
#     # Split resume text into lines
#     lines = text.split("\n")
# 
#     bullets = []
# 
#     # Identify lines that look like bullet points
#     for line in lines:
#         if len(line.strip()) > 30:
#             bullets.append(line.strip())
# 
#     return bullets
# 
# 
# # ---------------------------------
# # Upload resume file
# # ---------------------------------
# uploaded_file = st.file_uploader(
#     "Upload your resume",
#     type=["pdf", "txt"]
# )
# 
# 
# # Run the analysis if a file is uploaded
# if uploaded_file:
# 
#     # Extract resume text depending on file type
#     if uploaded_file.type == "application/pdf":
#         resume_text = extract_text(uploaded_file)
#     else:
#         resume_text = uploaded_file.read().decode()
# 
# 
#     # Display extracted text
#     st.subheader("📄 Extracted Resume Text")
#     st.text_area("Resume Content", resume_text, height=250)
# 
# 
#     # Calculate resume score
#     score = score_resume(resume_text)
# 
#     st.subheader("📊 Resume Score")
# 
#     # Show progress bar
#     st.progress(score)
# 
#     # Show score number
#     st.write(f"Score: **{score}/100**")
# 
# 
#     # Display feedback based on score
#     if score < 50:
#         st.warning("Your resume needs major improvements.")
#     elif score < 75:
#         st.info("Your resume is decent but can be improved.")
#     else:
#         st.success("Great resume!")
# 
# 
#     # ---------------------------
#     # Show improvement suggestions
#     # ---------------------------
#     st.subheader("💡 Resume Suggestions")
# 
#     suggestions = get_suggestions(resume_text)
# 
#     for s in suggestions:
#         st.write("✔", s)
# 
# 
#     # ---------------------------
#     # Improve resume bullet points
#     # ---------------------------
#     st.subheader("✨ Improved Resume Bullet Points")
# 
#     bullets = extract_bullets(resume_text)
# 
#     # Button to trigger AI improvement
#     if st.button("Improve Resume Bullet Points"):
# 
#         # Improve first 5 bullet points
#         for bullet in bullets[:5]:
# 
#             improved = improve_bullet(bullet)
# 
#             # Show original text
#             st.write("🔹 Original:")
#             st.write(bullet)
# 
#             # Show AI improved version
#             st.write("✅ Improved:")
#             st.success(improved)
# 
#             st.write("---")
#

!pkill -f flask || echo "No flask running"
!pkill -f ngrok || echo "No ngrok running"

# 🔎 List processes using port 5000
!lsof -i :5000

# ❌ Kill process by PID (replace 12345 with actual PID from previous cell)
!kill -9 11580

from pyngrok import ngrok
import os

ngrok.set_auth_token("3AtfQKDwO9z3gKtIZ3ChEGg0GFy_4bNVY8LNT8zycdPFvWTDN")

public_url = ngrok.connect(8501)
print("Open this URL:", public_url)

os.system("streamlit run app.py &")

